{
 "title": "MySpeed",
 "description": "Dashboard for MySpeed with Prometheus:\r\n\r\nhttps://github.com/gnmyt/myspeed",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(myspeed_ping,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Server-ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myspeed_server", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "myspeed_download{instance=\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "myspeed_upload{instance=\"$Instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myspeed_ping{instance=\"$Instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Test-Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "myspeed_time{instance=\"$Instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}