[general]
# Использовать промежуточный прокси (помогает скрывать трафик)
use_middle_proxy = true
# Глобальный рекламный тег (ad_tag) по умолчанию, если не задан индивидуальный тег для пользователя
# ad_tag = "00000000000000000000000000000000"
# Индивидуальные теги задаются в [access.user_ad_tags] (32 символа hex из @MTProxybot)
# Доступные уровни: debug (отладка) | verbose (подробный) | normal (обычный) | silent (без логов)
log_level = "debug"

[general.modes]
# Классический режим (устарел)
classic = false
# Безопасный режим (промежуточный вариант)
secure = false
# Режим TLS (наиболее современный и скрытный)
tls = true

[access.users]
# Список пользователей. Формат: "имя" = "HEX_32"
# Сгенерировать секрет: openssl rand -hex 16 или xxd -l 16 -p /dev/urandom
admin = "00000000000000000000000000000000"
public = "00000000000000000000000000000000"

[censorship]
# Домен, под который будет маскироваться TLS-трафик (рекомендуется реальный популярный ресурс)
# tls_domain = "petrovich.ru"
tls_domain = "lemanapro.ru"
# Включить общую маскировку
mask = true
# Эмуляция TLS (запрашивает реальные длины сертификатов и имитирует структуру TLS-записей)
tls_emulation = true
# Директория для кэширования данных эмуляции TLS
tls_front_dir = "tlsfront"

# [access.user_max_unique_ips]
# Ограничить количество уникальных IP-адресов для каждого пользователя
# admin = 5
# public = 10

[server]
# Основной порт, на котором будет работать прокси
port = 4343
# proxy_protocol = false                            # Включите, если прокси стоит за HAProxy или nginx с поддержкой PROXY protocol
# metrics_port = 9090                               # Порт для прослушивания метрик
metrics_listen = "0.0.0.0:9090"                     # Адрес для прослушивания метрик (приоритетнее, чем metrics_port)
metrics_whitelist = ["127.0.0.1", "172.16.0.0/12"]  # Список разрешенных IP для доступа к метрикам (localhost и подсеть docker)
max_connections = 10000                             # Ограничивает общее количество активных подключений к серверу

# Настройка прослушивания на нескольких интерфейсах/IP - IPv4
[[server.listeners]]
ip = "0.0.0.0"

[server.api]
# Включить API управления
enabled = true
# Адрес и порт для API
listen = "0.0.0.0:9091"
# Список разрешенных IP для доступа к API
whitelist = ["127.0.0.0/8", "172.16.0.0/12"]
# Облегченный режим работы API
minimal_runtime_enabled = false
# Время жизни кэша для облегченного режима (в миллисекундах)
minimal_runtime_cache_ttl_ms = 1000

# curl -s 127.0.0.1:19091/v1/system/info | jq
# curl -s 127.0.0.1:19091/v1/limits/effective | jq
# curl -s 127.0.0.1:19091/v1/stats/summary | jq
# curl -s 127.0.0.1:19091/v1/stats/users | jq