apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../headlamp
- ../flannel

- ../provisioners/local
# - ../provisioners/nfs
# - ../provisioners/smb

- ../kube-metrics-server
- ../kube-state-metrics
- ../event-exporter