apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../headlamp
- ../flannel

# Storages
- ../provisioners/local
# - ../provisioners/nfs
# - ../provisioners/smb
# - ../longhorn

# Monitoring
- ../kube-metrics-server
- ../kube-state-metrics
- ../event-exporter

# DevOps
- ../vault-agent-injector
- ../reloader
- ../keel

# Network
# - ../metallb
# - ../traefik-ingress
# - ../istio