app:
  name: dozzle
  namespace: monitoring
  image: amir20/dozzle
  version: v10.4
  authProvider: simple

rbac:
  sa: dozzle-pod-viewer-sa
  create: true

service:
  port: 80
  targetPort: 8080
  nodeShare: 
    enabled: true
    nodePort: 30080
  annotations:
    metallb.universe.tf/address-pool: "default-pool"
    metallb.universe.tf/loadBalancerIPs: "192.168.3.202"

ingress:
  enabled: true
  className: traefik
  host: dozzle.k8s.local