apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
spec:
  project: default
  syncPolicy: {}
  source:
    path: Kubernetes/provisioners/local
    repoURL: https://github.com/Lifailon/rudocs
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage