apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system-stack
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: Kubernetes/kube-system-stack
    repoURL: https://github.com/Lifailon/rudocs
    targetRevision: main
  sources: []
  project: default
  syncPolicy: {}