apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-metrics-server
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  source:
    path: Kubernetes/kube-metrics-server
    repoURL: https://github.com/Lifailon/rudocs
    targetRevision: main
  sources: []
  project: default
  syncPolicy: {}