apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diun
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://github.com/Lifailon/rudocs
    path: Kubernetes/diun
    targetRevision: main
    helm:
      values: ''
      valueFiles:
        - values.yaml
      parameters:
        - name: app.secrets.telegram.chatIds
          value: ''
        - name: app.secrets.telegram.token
          value: ''
  sources: []
  project: default
  syncPolicy: {}