apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diun
spec:
  source:
    repoURL: https://github.com/Lifailon/rudocs
    path: Kubernetes/diun
    targetRevision: rsa
    helm:
      values: ''
      valueFiles:
        - values.yaml
      parameters:
        - name: secrets.telegram.id
          value: 'test'
        - name: secrets.telegram.token
          value: test
  destination:
    server: https://kubernetes.default.svc
    targetRevision: main
  sources: []
  project: default
  syncPolicy: {}