apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diun
spec:
  project: default
  syncPolicy: {}
  source:
    repoURL: https://github.com/Lifailon/rudocs
    path: Kubernetes/diun
    targetRevision: main
    helm:
      values: ""
      valueFiles:
        - values.yaml
      parameters:
        - name: app.secrets.telegram.chatIds
          value: ""
        - name: app.secrets.telegram.token
          value: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring