apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flannel
spec:
  destination:
    namespace: kube-flannel
    server: https://kubernetes.default.svc
  source:
    path: Kubernetes/flannel
    repoURL: https://github.com/Lifailon/rudocs
    targetRevision: main
  sources: []
  project: default
  syncPolicy: {}