apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
spec:
  project: default
  syncPolicy: {}
  source:
    path: Kubernetes/kube-state-metrics
    repoURL: https://github.com/Lifailon/rudocs
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system