apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dozzle
spec:
  project: default
  syncPolicy:
    automated:
      enabled: false
  syncOptions:
    - CreateNamespace=true
  source:
    path: Kubernetes/dozzle
    repoURL: https://github.com/Lifailon/rudocs
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring