app:
  name: gatus
  namespace: monitoring
  replicas: 1
  revisionCount: 1
  imagePullPolicy: Always
  image: twinproduction/gatus
  version: v5.35.0
  annotations:
    reloader.stakater.com/auto: "true"
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  probes:
    liveness:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
  env:
    HTTP_PROXY: http://192.168.3.105:20171
    HTTPS_PROXY: http://192.168.3.105:20171
    NO_PROXY: "kubernetes.default,svc.cluster.local,cluster.local,localhost,10.96.0.1,127.0.0.1,192.168.3.0/24"
  config:
    WEB_UI_AUTH: false
    WEB_UI_USERNAME: admin
    WEB_UI_PASSWORD: JDJ5JDA5JGdXQ2VjM3hkb2o2ZWN5enAwbnlCT09aMUdLUEYxM2FOM3ZBVGRSdkJiNTljWVhQSU5xYzh1
    TELEGRAM_API_KEY: ""
    TELEGRAM_CHAT_ID: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  nodePort: 30081
  annotations:
    metallb.universe.tf/address-pool: "default-pool"
    metallb.universe.tf/loadBalancerIPs: "192.168.3.205"

ingress:
  enabled: true
  className: traefik
  host: gatus.k8s.local