apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  {{- with .Values.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end}}
spec:
  replicas: {{ .Values.app.replicas }}
  revisionHistoryLimit: {{ .Values.app.revisionCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
      # annotations:
      #   config/checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}:{{ .Values.app.version }}
          imagePullPolicy: {{ .Values.app.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}
              name: http
              protocol: TCP
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.app.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $val := .Values.app.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.app.name }}-config-volume
              mountPath: /config
            {{- if .Values.app.volume.hostPath.enabled }}
            - name: diun-data
              mountPath: /data
            {{- end }}
      volumes:
        - name: {{ .Values.app.name }}-config-volume
          configMap:
            name: {{ .Values.app.name }}-config
        {{- if .Values.app.volume.hostPath.enabled }}
        - name: diun-data
          hostPath:
            path: {{ .Values.app.volume.hostPath.path }}
            type: DirectoryOrCreate
        {{- end }}
      {{- with .Values.app.volume.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}