{
 "title": "Docker Exporter (cadvisor)",
 "description": "Fork https://grafana.com/grafana/dashboards/13496-docker-and-system-monitoring",
 "tags": [ "Docker" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(cadvisor_version_info,instance)"
    }
   },
   { "name": "Container", "query": { "query": "label_values(name)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Info Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "(time() - container_start_time_seconds{instance=~\"$Node\",name=~\"$Container\"})/86400",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"$Node\",name=~\".+\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$Node\",name=~\"$Container\"}[$interval])) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$Node\",name=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "Received Network Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$Node\",name=~\"$Container\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Sent Network Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$Node\",name=~\"$Container\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$Node\",name=~\"$Container\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$Node\",name=~\"$Container\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$Node\",name=~\"$Container\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$Node\",name=~\"$Container\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Heatmap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Usage per Container",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$Node\",name=~\"$Container\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "heatmap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(container_memory_rss{instance=~\"$Node\",name=~\"$Container\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$Node\",name=~\"$Container\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$Node\",name=~\"$Container\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}