{
 "title": "ohm-influx",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE app = 'ohm'\n"
   },
   {
    "name": "power",
    "query": "show tag values from Power with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "temperature",
    "query": "show tag values from Temperature with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "volts",
    "query": "show tag values from Voltage with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "network",
    "query": "show tag values with key = hardware WHERE hardware_type = 'NIC' and app = 'ohm'"
   },
   {
    "name": "fan",
    "query": "show tag values from Fan with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "control",
    "query": "show tag values from Control with key = hardware_type WHERE app = 'ohm'"
   },
   {
    "name": "hertz",
    "query": "show tag values from Clock with key = hardware_type WHERE app = 'ohm'"
   }
  ]
 },
 "panels": [
  { "title": "Load Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "CPU Load",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "CPU" },
      { "condition": "AND", "key": "sensor", "operator": "=", "value": "CPU Total" }
     ]
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "RAM" }
     ]
    }
   ]
  },
  {
   "title": "RAM Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 8, "y": 1 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "GpuNvidia" }
     ]
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "HDD" }
     ]
    }
   ]
  },
  { "title": "Load Breakdown", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "CPU" },
      { "condition": "AND", "key": "sensor", "operator": "!=", "value": "CPU Total" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "GpuNvidia" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Load",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "GpuAti" }
     ]
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "gbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_sensor",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "sensor" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "Data",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$instance$/" },
        { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "RAM" }
       ]
      }
     ]
    },
    {
     "title": "GPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_sensor",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "sensor" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "SmallData",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$instance$/" },
        { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "GpuNvidia" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Watts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$power Wattage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "power",
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=~", "value": "/^$power$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$temperature Temperatures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "repeat": "temperature",
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=~", "value": "/^$temperature$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "Volts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "$volts Volts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "repeat": "volts",
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=~", "value": "/^$volts$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "Network Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "$network Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "repeat": "network",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Throughput",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=", "value": "NIC" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "hardware", "operator": "=~", "value": "/^$network$/" }
     ]
    }
   ]
  },
  { "title": "Fan RPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "$fan RPM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "repeat": "fan",
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Fan",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=~", "value": "/^$fan$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "$control Control",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "repeat": "control",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Control",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=~", "value": "/^$control$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  { "title": "Frequencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "$hertz Frequencies",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "repeat": "hertz",
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Clock",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=", "value": "ohm" },
      { "condition": "AND", "key": "hardware_type", "operator": "=~", "value": "/^$hertz$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}