{
 "title": "Windows (Open Hardware Monitor)",
 "tags": [ "Windows" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "{__name__=~\"ohm_.*\"}"
    }
   },
   {
    "name": "hdd",
    "query": {
     "query": "{__name__=~\"ohm_hdd_.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "{__name__=~\"ohm_nic_.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "{__name__=~\"ohm_cpu_.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "{__name__=~\"ohm_gpu.*\",instance=\"$instance\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 22, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(label_replace(label_join({instance=\"$instance\",__name__=~\"ohm_.*_celsius\"}, \"Hardware\", \" \", \"hardware\", \"sensor\"), \"__SensorGroup\", \"$1$2\", \"sensor\", \"(.*)#[0-9]*(.*)\"), \"__SensorID\", \"$2\", \"sensor\", \"(.*#)([0-9]*)(.*)\")"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{instance=\"$instance\",sensor=\"CPU Total\"}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_ram_load_percent{instance=\"$instance\",sensor=\"Memory\"}"
    }
   ]
  },
  {
   "title": "GPU Compute",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_load_percent{instance=\"$instance\",sensor=\"GPU Core\"} or ohm_gpuati_load_percent{instance=\"$instance\",sensor=\"GPU Core\"}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_gpunvidia_bytes{instance=\"$instance\",sensor=\"GPU Memory Used\"} * 100 / ignoring(sensor) ohm_gpunvidia_bytes{instance=\"$instance\",sensor=\"GPU Memory Total\"} or ohm_gpuati_bytes{instance=\"$instance\",sensor=\"GPU Memory Used\"} * 100 / ignoring(sensor) ohm_gpuati_bytes{instance=\"$instance\",sensor=\"GPU Memory Total\"}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ohm_hdd_bytes{instance=\"$instance\", sensor=\"Data Read\"}[$__range]))",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Downloaded\"}[$__range]))",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Network Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ohm_nic_bytes_per_second{instance=\"$instance\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ohm_hdd_bytes{instance=\"$instance\", sensor=\"Data Written\"}[$__range]))",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Uploads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Uploaded\"}[$__range]))",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Disk Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ohm_hdd_bytes_per_second{instance=\"$instance\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Max Disk Space",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ohm_hdd_load_percent{instance=\"$instance\",sensor=\"Used Space\"})"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ohm_nic_load_percent{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ohm_hdd_load_percent{instance=\"$instance\",sensor=\"Total Activity\"})"
    }
   ]
  },
  {
   "title": "Max Fan",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max({__name__=~\"ohm_.*_control_percent\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Component Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ohm_cpu_watts{instance=\"$instance\", sensor=~\".*Package\"} + ignoring(sensor, hw_instance, hardware) (ohm_gpunvidia_watts{instance=\"$instance\"} or ohm_gpuati_watts{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Media Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ohm_hdd_factor{instance=\"$instance\",sensor=\"Media Errors\"})",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Drives",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max by (hardware,hw_instance) (ohm_hdd_celsius{instance=\"$instance\"})"
    },
    {
     "expr": "ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Read\"}"
    },
    {
     "expr": "ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Written\"}"
    },
    {
     "expr": "sum by (hardware,hw_instance) (increase(ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Read\"}[$__range]))"
    },
    {
     "expr": "sum by (hardware,hw_instance) (increase(ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Written\"}[$__range]))"
    },
    {
     "expr": "ohm_hdd_load_percent{instance=\"$instance\",sensor=\"Used Space\"}"
    },
    {
     "expr": "ohm_hdd_factor{instance=\"$instance\",sensor=\"Power Cycles\"}"
    },
    {
     "expr": "ohm_hdd_factor{instance=\"$instance\",sensor=\"Media Errors\"}"
    }
   ]
  },
  {
   "title": "CPU: $cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "cpu",
   "collapsed": true,
   "panels": [
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(ohm_cpu_load_percent{instance=\"$instance\", sensor!=\"CPU Total\"}, \"_sensor\", \"${1}0$2$3\", \"sensor\", \"(.*?)(\\\\d{1})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}$2$3\", \"sensor\", \"(.*?)(\\\\d{2})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}\", \"sensor\", \"([^\\\\d]*?)\")",
       "legendFormat": "{{_sensor}}"
      }
     ]
    },
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(ohm_cpu_celsius{instance=\"$instance\"}, \"_sensor\", \"$3 ${1}0$2\", \"sensor\", \"(.*?)(\\\\d{1})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"$3 ${1}$2\", \"sensor\", \"(.*?)(\\\\d{2})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}\", \"sensor\", \"([^\\\\d]*?)\")",
       "legendFormat": "{{_sensor}}"
      }
     ]
    },
    {
     "title": "Frequencies",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(ohm_cpu_hertz{instance=\"$instance\"}, \"_sensor\", \"$3 ${1}0$2\", \"sensor\", \"(.*?)(\\\\d{1})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"$3 ${1}$2\", \"sensor\", \"(.*?)(\\\\d{2})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}\", \"sensor\", \"([^\\\\d]*?)\")",
       "legendFormat": "{{_sensor}}"
      }
     ]
    },
    {
     "title": "Wattage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ohm_cpu_watts{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Volts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(ohm_cpu_volts{instance=\"$instance\"}, \"_sensor\", \"$3 ${1}0$2\", \"sensor\", \"(.*?)(\\\\d{1})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"$3 ${1}$2\", \"sensor\", \"(.*?)(\\\\d{2})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}\", \"sensor\", \"([^\\\\d]*?)\")",
       "legendFormat": "{{_sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU: $gpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "gpu",
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Load",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 314 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_load_percent{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_load_percent{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 325 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_celsius{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_celsius{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Frequencies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 325 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_hertz{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_hertz{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 334 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_bytes{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_bytes{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Fan",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 334 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_revolutions_per_minute{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "Fan"
      },
      {
       "expr": "(max_over_time(ohm_gpunvidia_revolutions_per_minute{instance=\"$instance\"}[$__range]) / (max_over_time(ohm_gpunvidia_control_percent{instance=\"$instance\"}[$__range]) / 100)) * 0.9",
       "legendFormat": "High RPM"
      },
      {
       "expr": "ohm_gpuati_revolutions_per_minute{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "Fan"
      },
      {
       "expr": "(max_over_time(ohm_gpuati_revolutions_per_minute{instance=\"$instance\"}[$__range]) / (max_over_time(ohm_gpuati_control_percent{instance=\"$instance\"}[$__range]) / 100)) * 0.9",
       "legendFormat": "High RPM"
      }
     ]
    },
    {
     "title": "Wattage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 342 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_watts{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_watts{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 342 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_bytes_per_second{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_bytes_per_second{instance=\"$instance\",hw_instance=\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drive: $hdd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "hdd",
   "collapsed": true,
   "panels": [
    {
     "title": "$hdd Factors",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 351 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "ohm_hdd_factor{instance=\"$instance\",hw_instance=\"$hdd\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 351 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ohm_hdd_celsius{instance=\"$instance\",hw_instance=\"$hdd\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Disk Activity Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ohm_hdd_load_percent{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Total Activity\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "ohm_hdd_load_percent{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Write Activity\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Disk Activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 376 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "ohm_hdd_bytes_per_second{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Read Rate\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "-ohm_hdd_bytes_per_second{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Write Rate\"}",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  },
  {
   "title": "Motherboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 455 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ohm_superio_celsius{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Volts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 466 },
     "repeat": "volts",
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "ohm_superio_volts{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Fan",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 466 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "ohm_superio_revolutions_per_minute{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "(max(ohm_superio_revolutions_per_minute{instance=\"$instance\"}) / ignoring(sensor) (max(ohm_superio_control_percent{instance=\"$instance\"}) / 100)) * 0.9",
       "legendFormat": "High RPM"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 456 },
     "targets": [
      {
       "expr": "sum by (hardware) (increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Downloaded\"}[$__range]))"
      },
      {
       "expr": "sum by (hardware) (increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Uploaded\"}[$__range]))"
      },
      {
       "expr": "ohm_nic_load_percent{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "$network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 464 },
     "repeat": "network",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Download Speed\"}",
       "legendFormat": "Download"
      },
      {
       "expr": "-ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Upload Speed\"}",
       "legendFormat": "Upload"
      }
     ]
    }
   ]
  }
 ]
}