apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-operator
  template:
    metadata:
      labels:
        app: event-operator
    spec:
      # SA с правами выполнения kubectl get events
      serviceAccountName: event-exporter-sa
      containers:
      - name: operator
        image: lifailon/event-operator:v1
        # Прокидываем переменные окружения из секрета в контейнер
        env:
        - name: TELEGRAM_API_KEY
          valueFrom:
            secretKeyRef:
              name: telegram-secrets
              key: TELEGRAM-API-KEY
        - name: TELEGRAM_CHAT_ID_DEFAULT
          valueFrom:
            secretKeyRef:
              name: telegram-secrets
              key: TELEGRAM-CHAT-ID