apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-notify-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-notify-operator
  template:
    metadata:
      labels:
        app: event-notify-operator
    spec:
      # SA с правами выполнения kubectl get events
      # serviceAccountName: event-exporter-sa
      serviceAccountName: event-notify-operator-sa
      containers:
        - name: operator
          image: lifailon/event-notify-operator:v1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            # Прокидываем переменную окружения из секрета в контейнер
            - name: SHOUTRRR_TELEGRAM
              valueFrom:
                secretKeyRef:
                  name: shoutrrr-secrets
                  key: SHOUTRRR-TELEGRAM
            # Статическая переменная для фильтрации событий
            - name: WARNING_ONLY
              value: "false"
            # Стандартные переменные для настройки пересылки трафика через прокси сервер и исключения
            - name: HTTPS_PROXY
              value: http://192.168.3.105:20171
            - name: NO_PROXY
              value: kubernetes.default,svc.cluster.local,cluster.local,localhost,10.96.0.1,127.0.0.1,192.168.3.0/24