apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: shoutrrr-secrets
  namespace: monitoring
stringData:
  SHOUTRRR-TELEGRAM: "telegram://123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11@telegram?channels=-100123456789"