[Definition]
failregex = ^.*from (?:tcp|udp):<HOST>:\d+ rejected.*proxy/socks.*invalid username or password.*$
# 2026/04/01 22:25:00.444801 from tcp:94.25.174.105:27840 rejected  proxy/socks: invalid username or password