services:
  openserp:
    image: karust/openserp:latest
    container_name: serp
    restart: unless-stopped
    shm_size: 2gb
    command: serve -l
    ports:
      - 7000:7000
    environment:
      OPENSERP_SERVER_HOST: "0.0.0.0"
      OPENSERP_SERVER_PORT: 7000
      OPENSERP_BAIDU_RATE_REQUESTS: 6
      OPENSERP_BAIDU_RATE_BURST: 2
    volumes:
      - ./config.yaml:/usr/src/app/config.yaml:ro