# Сгенерировать временный JWT-токен, который не хранится в базе данных Kubernetes как объект
# kubectl create token headlamp-admin -n kube-system --duration=43800h

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: headlamp-admin-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: headlamp-admin

# Получить токен доступа из секрета
# kubectl get secret headlamp-admin-token -n kube-system -o jsonpath='{.data.token}' | base64 --decode