metrics: true

# storage:
#   type: sqlite
#   path: /data/data.db

# htpasswd -nbBC 9 admin GatusAdmin | cut -d: -f2 | tr -d '\n' | base64 | tr -d '\n'
{{- if .Values.app.config.WEB_UI_AUTH }}
security:
  basic:
    username: {{ .Values.app.config.WEB_UI_USERNAME | quote }}
    password-bcrypt-base64: {{ .Values.app.config.WEB_UI_PASSWORD | quote }}
{{- end }}

alerting:
  telegram:
    token: {{ .Values.app.config.TELEGRAM_API_KEY | quote }}
    id: {{ .Values.app.config.TELEGRAM_CHAT_ID | quote }}

endpoints:
  - name: "Google ICMP"
    group: external
    url: icmp://8.8.8.8
    interval: 10s
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
        enabled: true
        failure-threshold: 3
        success-threshold: 3
        minimum-reminder-interval: 30m
        send-on-resolved: true

  - name: "Google DNS"
    group: external
    url: 8.8.8.8
    interval: 10s
    dns:
      query-name: google.com
      query-type: A
    conditions:
      - "[CONNECTED] == true"
      - "[DNS_RCODE] == NOERROR"
    alerts:
      - type: telegram
        enabled: true
        failure-threshold: 3
        success-threshold: 3
        minimum-reminder-interval: 30m
        send-on-resolved: true

  - name: "GitHub"
    group: external
    url: https://github.com
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2s"
      - "[CERTIFICATE_EXPIRATION] > 168h"
    alerts:
      - type: telegram
        enabled: true
        failure-threshold: 3
        success-threshold: 3
        minimum-reminder-interval: 30m
        send-on-resolved: true

  - name: "Docker Hub"
    group: external
    url: https://hub.docker.com
    interval: 10m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2s"
      - "[CERTIFICATE_EXPIRATION] > 168h"
    alerts:
      - type: telegram
        enabled: true
        failure-threshold: 3
        success-threshold: 3
        minimum-reminder-interval: 30m
        send-on-resolved: true

  - name: "Telegram API"
    group: external
    url: https://api.telegram.org
    interval: 10m
    # client:
    #   proxy-url: http://192.168.3.105:20171
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2s"
      - "[CERTIFICATE_EXPIRATION] > 168h"
    alerts:
      - type: telegram
        enabled: true
        failure-threshold: 3
        success-threshold: 3
        minimum-reminder-interval: 30m
        send-on-resolved: true

  - name: "HTTPBin"
    group: external
    url: https://httpbingo.org/anything
    interval: 10m
    headers:
      User-Agent: "curl/8.9.1"
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2s"
      - "[CERTIFICATE_EXPIRATION] > 168h"
      - "len([BODY].headers) > 10"
      - "[BODY].headers.User-Agent == [curl/8.9.1]"
      - "has([BODY].method) == true"
      - "[BODY].method == GET"
      - "[BODY].url == pat(https://httpbin*)"
      - "[BODY].url == any(https://httpbingo.org/anything,https://httpbin.org/anything)"

  # HTTP Kubernetes cluster health check
  - name: "node-01 (hv-us-101)"
    group: internal
    url: "https://192.168.3.101:6443/healthz"
    interval: 30s
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
      - "[BODY] == ok"
    alerts:
      - type: telegram
        enabled: true
        failure-threshold: 3
        success-threshold: 3
        minimum-reminder-interval: 30m
        send-on-resolved: true

  # SSH TCP port check
  - name: "node-02 (rpi-105)"
    group: internal
    url: tcp://192.168.3.105:2121
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
    alerts:
      - type: telegram
        enabled: true
        failure-threshold: 3
        success-threshold: 3
        minimum-reminder-interval: 30m
        send-on-resolved: true

  # SSH connection
  - name: "node-03 (rpi-106)"
    group: internal
    url: ssh://192.168.3.106:2121
    interval: 1m
    ssh:
      username: ""
      password: ""
      private-key: ""
    # body: |
    #   {
    #     "command": "echo '{\"memory\": {\"used\": 512}}'"
    #   }
    conditions:
      - "[CONNECTED] == true"
      - "[STATUS] == 0"
      # - "[BODY].memory.used > 500"
    alerts:
      - type: telegram
        enabled: true
        failure-threshold: 3
        success-threshold: 3
        minimum-reminder-interval: 30m
        send-on-resolved: true

# tunneling:
#   vps-tun:
#     type: SSH
#     host: "external-ip"
#     port: 22
#     username: "monitoring"
#     password: "password"
#     private-key: |
#       -----BEGIN RSA PRIVATE KEY-----
#       -----END RSA PRIVATE KEY-----

# endpoints:
#   - name: "VPS K8S Health Check"
#     group: vps
#     url: "https://internal-ip:port/healthz"
#     interval: 30s
#     client:
#       tunnel: "vps-tun"
#     conditions:
#       - "[STATUS] == 200"
#       - "[BODY] == ok"