modules:
  icmp_ping:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"

  tcp_ssh:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"
      query_response:
        - expect: "^SSH"

  http_2xx:
    prober: http
    timeout: 5s
    http:
      tls_config:
        insecure_skip_verify: true
      method: GET
      headers:
        Content-Type: "application/json"
      no_follow_redirects: false
      valid_status_codes: []
      # valid_status_codes: [200]
      # fail_if_body_not_matches_regexp:
      #   - '.+Provider.+'