services:
  volume-permissions-update:
    image: alpine
    container_name: volume-permissions-update
    restart: no
    volumes:
      - ./grafana_data:/grafana_data
      - ./grafana_dashboards:/grafana_dashboards
      - ./grafana-provider.yaml:/grafana-provider.yaml
      - ./grafana-datasources.yaml:/grafana-datasources.yaml
      - ./prometheus_data:/prometheus_data
      - ./prometheus.yml:/prometheus.yml
      - ./alert-rules.yml:/alert-rules.yml
      - ./alertmanager.yml:/alertmanager.yml
      - ./telegram.tmpl:/telegram.tmpl
      - ./loki_data:/loki_data
    command: |
      sh -c "
        chown -R 472:472 /grafana_data /grafana_dashboards grafana-provider.yaml grafana-datasources.yaml
        chown -R 65534:65534 /prometheus_data /prometheus.yml /alert-rules.yml /alertmanager.yml /telegram.tmpl
        chown -R 1000:1000 loki_data
        echo 'Volume permissions updated successfully.'
        exit 0
      "

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: 472:472
    ports:
      - 9089:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      # docker exec -it grafana grafana cli admin reset-admin-password GrafanaAdminNew
      - GF_SECURITY_ADMIN_PASSWORD=GrafanaAdmin
      # - GF_DATABASE_TYPE=postgres
      # - GF_DATABASE_HOST=grafana-db:5432
      # - GF_DATABASE_NAME=grafana
      # - GF_DATABASE_USER=grafana
      # - GF_DATABASE_PASSWORD=grafana
      # - GF_DATABASE_SSL_MODE=disable
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana_dashboards:/var/lib/grafana/dashboards
      - ./grafana-provider.yaml:/etc/grafana/provisioning/dashboards/provider.yaml
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      volume-permissions-update:
        condition: service_completed_successfully

  # grafana-db:
  #   image: postgres:latest
  #   container_name: grafana-db
  #   restart: always
  #   environment:
  #     POSTGRES_DB: grafana
  #     POSTGRES_USER: grafana
  #     POSTGRES_PASSWORD: grafana
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    user: 65534:65534
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules.yml:/etc/prometheus/alert.yml
      - ./prometheus_data:/prometheus
    ports:
      - 9090:9090
    # dns:
    #   - 192.168.3.101
    depends_on:
      volume-permissions-update:
        condition: service_completed_successfully

  # pushgateway:
  #   image: prom/pushgateway:latest
  #   container_name: pushgateway
  #   restart: always
  #   ports:
  #     - 9091:9091

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    restart: always
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      # Custom template
      - ./telegram.tmpl:/etc/alertmanager/telegram.tmpl
    ports:
      - 9093:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    restart: always
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    ports:
      - 9115:9115
    command:
      - --config.file=/etc/blackbox_exporter/config.yml

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    # ports:
    #   - 9100:9100

  process-exporter:
    image: ncabatoff/process-exporter
    container_name: process-exporter
    restart: always
    privileged: true
    volumes:
      - /proc:/host/proc
      - ./proc-conf.yml:/conf.yml
    # ports:
    #   - 9256:9256
    command:
      - -procfs
      - /host/proc
      - -config.path
      - /conf.yml

  beyla-exporter:
    image: grafana/beyla:latest
    container_name: beyla-exporter
    restart: always
    privileged: true
    pid: host
    environment:
      - BEYLA_OPEN_PORT=1-65535
      - BEYLA_PROMETHEUS_PORT=8080
    # ports:
    #   - 9876:8080

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   restart: always
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   # ports:
  #   #   - 8080:8080

  # Docker Exporter
  logporter:
    image: lifailon/logporter:latest
    container_name: logporter
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # ports:
    #   - 9333:9333

  # Log server
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: always
    user: root
    volumes:
      - ./loki.yml:/etc/loki/loki-config.yaml
      - ./loki_data:/loki
    ports:
      - 3100:3100

  # Log agent
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail.yml:/etc/promtail/promtail.yml
      - /etc/hostname:/etc/hostname:ro
    command: -config.file=/etc/promtail/promtail.yml
    # ports:
    #   - 9080:9080

  # fluent-bit:
  #   image: fluent/fluent-bit:latest
  #   container_name: fluent-bit
  #   restart: always
  #   user: root
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
  #     - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
  #   logging:
  #     driver: local