apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system
metadata:
  name: metallb-kustomization

resources:
- crd.yaml
- webhook.yaml
- rbac.yaml
- configmap.yaml
- deployment.yaml
- daemon-set.yaml
- service.yaml

# Создать новый пул адресов
- ip-address-pool.yaml
# Разрешить анонсирование IP-адресов из default-pool в локальной сети через протокол ARP
- l2-advertisement.yaml

# Пробросить метрики через Ingress
# - metrics-ingress.yaml
# - metrics-middleware.yaml