apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rest-api
commonLabels:
  app: torapi
  app.kubernetes.io/managed-by: kustomize

helmCharts:
  - name: .
    releaseName: torapi
    valuesFile: values.yaml