apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: .

helmCharts:
  - name: ingress
    includeCRDs: true
    releaseName: istio-ingress
    additionalValuesFiles:
      - ./ingress/values.yaml
  - name: egress
    includeCRDs: true
    releaseName: istio-egress
    additionalValuesFiles:
      - ./egress/values.yaml