{
 "title": "Speedtest-Exporter",
 "description": "Dashboard for Speedtest Exporter https://github.com/MiguelNdeCarvalho/speedtest-exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(speedtest_up, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(speedtest_up, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Gauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Exporter",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_up{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Last Server ID",
   "type": "stat",
   "description": "ServerID of the last test done",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "speedtest_server_id{instance=\"$instance\", job=\"$job\"}"
    }
   ]
  },
  { "title": "Graphics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Download and Upload Speed (Mbits/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "speedtest_download_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6",
     "legendFormat": "Download Speed (Mbits/s)"
    },
    {
     "expr": "speedtest_upload_bits_per_second{instance=\"$instance\", job=\"$job\"}*10^-6",
     "legendFormat": "Upload Speed (Mbits/s)"
    }
   ]
  },
  {
   "title": "Ping and Jitter (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "speedtest_ping_latency_milliseconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Ping (ms)"
    },
    {
     "expr": "speedtest_jitter_latency_milliseconds{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Jitter (ms)"
    }
   ]
  }
 ]
}