apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-checker
  namespace: telegram
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: vault-checker
  template:
    metadata:
      labels:
        app: vault-checker
      annotations:
        # Включаем Vault Agent Sidecar
        vault.hashicorp.com/agent-inject: "true"
        # Заставляет контейнеры ждать, пока vault-agent-init не завершится успешно (когда файл записан на диск)
        vault.hashicorp.com/agent-init-first: 'true'
        # Роль доступа к секретам Vault
        vault.hashicorp.com/role: "tg-app-role"
        # Определяем название файла (/vault/secrets/env.txt) и путь к секрету в Vault 
        vault.hashicorp.com/agent-inject-secret-env.txt: "k8s/app/telegram-bot"
        # Шаблон для парсинга выходного файла с содержимым секретов в формте ключ=значение
        vault.hashicorp.com/agent-inject-template-env.txt: |
          {{- with secret "k8s/data/app/telegram-bot" -}}
          {{- range $key, $value := .Data.data }}
          {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end -}}
        vault.hashicorp.com/agent-requests-cpu: 100m
        vault.hashicorp.com/agent-limits-cpu: 200m
        vault.hashicorp.com/agent-requests-mem: 64Mi
        vault.hashicorp.com/agent-limits-mem: 128Mi
        vault.hashicorp.com/log-level: debug
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: env-checker
          image: alpine:3.23
          command: ["sh", "-c", "source /vault/secrets/env.txt && echo $CHAT_ID && echo $API_KEY && sleep infinity"]
          livenessProbe:
            exec:
              command: ["sh", "-c", "test -s /vault/secrets/env.txt"]
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3