apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-checker
  namespace: telegram
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: vault-checker
  template:
    metadata:
      labels:
        app: vault-checker
      annotations:
        # Включаем Vault Agent Sidecar
        vault.hashicorp.com/agent-inject: "true"
        # Роль доступа к секретам Vault
        vault.hashicorp.com/role: "tg-app-role"
        # Определяем название файла (/vault/secrets/env.txt) и путь к секрету в Vault 
        vault.hashicorp.com/agent-inject-secret-env.txt: "k8s/app/telegram-bot"
        # Шаблон для парсинга выходного файла с содержимым секретов в формте ключ=значение
        vault.hashicorp.com/agent-inject-template-env.txt: |
          {{- with secret "k8s/data/app/telegram-bot" -}}
          {{- range $key, $value := .Data.data }}
          {{ $key }}="{{ $value }}"
          {{- end }}
          {{- end -}}
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: env-checker
          image: alpine:3.23
          # command: ["sh", "-c", "cat /vault/secrets/env.txt && sleep infinity"]
          command: ["sh", "-c", "source /vault/secrets/env.txt && echo $CHAT_ID && echo $API_KEY && sleep infinity"]