apiVersion: v1
kind: ConfigMap
metadata:
  name: diun-config
  namespace: default
data:
  DIUN_PROVIDERS_KUBERNETES: "true"
  DIUN_PROVIDERS_KUBERNETES_WATCHBYDEFAULT: {{ .Values.app.config.watch | default "true" | quote }}
  DIUN_WATCH_SCHEDULE: {{ .Values.app.config.scheduler | default "0 */6 * * *" | quote }}
  LOG_LEVEL: {{ .Values.app.config.logLevel | default "info" | quote }}
  LOG_JSON: {{ .Values.app.config.logJson | default "false" | quote }}
  TZ: {{ .Values.app.config.timezone | default "Etc/UTC" | quote }}