{{- with .Values.app.secrets.telegram }}
{{- if and .token .chatIds }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: diun-secret
data:
  DIUN_NOTIF_TELEGRAM_TOKEN: {{ .token | b64enc }}
  DIUN_NOTIF_TELEGRAM_CHATIDS: {{ .chatIds | toString | b64enc }}
{{- end }}
{{- end }}