apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: diun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
      annotations:
        diun.enable: "true"
    spec:
      serviceAccountName: diun
      restartPolicy: Always
      containers:
        - name: diun
          image: crazymax/diun:4.31
          imagePullPolicy: Always
          args: ["serve"]
          livenessProbe:
            exec:
              command: ["diun", "notif", "test"]
            initialDelaySeconds: 30
            periodSeconds: 86400
            timeoutSeconds: 10
            failureThreshold: 1
          readinessProbe:
            exec:
              command: ["diun", "notif", "test"]
            initialDelaySeconds: 30
            periodSeconds: 86400
            timeoutSeconds: 10
            failureThreshold: 1
          {{- if .Values.app.proxy.enabled }}
          env:
            {{- range $key, $val := .Values.app.proxy.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: diun-config
            {{- with .Values.app.secrets.telegram }}
            {{- if and .token .chatIds }}
            - secretRef:
                name: diun-secret
            {{- end }}
            {{- end }}