{
 "title": "Docker Exporter (logporter)",
 "description": "Source code: https://github.com/Lifailon/logporter",
 "tags": [ "Docker" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ContainerName",
    "query": {
     "query": "query_result(group by(containerName) (docker_cpu_usage_total))"
    }
   },
   {
    "name": "HostName",
    "query": {
     "query": "query_result(group by(hostname) (docker_cpu_usage_total))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_containers_up_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime Containers",
   "type": "stat",
   "gridPos": { "h": 12, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - docker_started_time{containerName=~\"$ContainerName\", hostname=~\"$HostName\"}",
     "legendFormat": "{{containerName}}"
    }
   ]
  },
  {
   "title": "CPU Total Usage",
   "type": "stat",
   "description": "Total cpu usage of all containers",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(docker_cpu_usage_total{hostname=~\"$HostName\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "description": "Total network usage of all containers",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(docker_network_received_bytes{hostname=~\"$HostName\"}[1m]))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(rate(docker_network_transmit_bytes{hostname=~\"$HostName\"}[1m]))",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Logs Count",
   "type": "timeseries",
   "description": "stdout + stderr",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "round(increase(docker_logs_all_count{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]))",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "PIDs Count",
   "type": "timeseries",
   "description": "Processes count",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "docker_process_pids_count{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "stat",
   "description": "Total memory usage of all containers relative to the maximum value per one container",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(docker_memory_usage{hostname=~\"$HostName\"}))/(max(docker_memory_total{hostname=~\"$HostName\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stopped Containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_containers_down_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "Total memory usage of all containers",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(docker_memory_usage{hostname=~\"$HostName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "stat",
   "description": "Total block storage usage of all containers",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(docker_io_read_bytes{hostname=~\"$HostName\"}[1m]))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(rate(docker_io_write_bytes{hostname=~\"$HostName\"}[1m]))",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "description": "Maximum memory per one container",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(docker_memory_total{hostname=~\"$HostName\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Total Usage",
   "type": "timeseries",
   "description": "User + Kernel = Total",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(docker_cpu_usage_total{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]) * 100",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Network Received KBytes",
   "type": "timeseries",
   "description": "Input from the network",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_network_received_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "description": "Input from the block storage",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_io_read_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Memory Usage (MByte)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "docker_memory_usage{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}/1024/1024",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Network Transmit KBytes",
   "type": "timeseries",
   "description": "Output to the network",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_network_transmit_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Disk Write KBytes",
   "type": "timeseries",
   "description": "Output to the block storage",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(docker_io_write_bytes{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[1m])",
     "legendFormat": "{{containerName}} ({{hostname}})"
    }
   ]
  },
  {
   "title": "Logged Messages Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs Standart count (stdout)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "round(increase(docker_logs_stdout_count{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]))",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "Logs Error count (stderr)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "round(increase(docker_logs_stderr_count{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]))",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU User and Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU User Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(docker_cpu_usage_user{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]) * 100",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "CPU Kernel Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(docker_cpu_usage_kernel{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval]) * 100",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Packages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Received Packages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(docker_network_received_packages{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval])",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    },
    {
     "title": "Network Transmit Packages",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(docker_network_transmit_packages{containerName=~\"$ContainerName\",hostname=~\"$HostName\"}[$__rate_interval])",
       "legendFormat": "{{containerName}} ({{hostname}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers Count History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Count",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "docker_containers_up_count+docker_containers_down_count",
       "legendFormat": "Total Containers"
      },
      { "expr": "docker_containers_up_count", "legendFormat": "Running Containers" }
     ]
    }
   ]
  }
 ]
}