apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: beszel-agent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
        - name: beszel-agent
          image: henrygd/beszel-agent:latest
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 45877
          env:
            - name: KEY
              value: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICY621efzKYU5D1qYOWsiL2d2QGx/O2IcMV2S4xPYyln"
            - name: LISTEN
              value: "45877"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists