apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
  users.yml: |
{{ .Files.Get "configs/users.yml" | indent 4 }}