services:
  # volume-permissions-update:
  #   image: alpine
  #   container_name: volume-permissions-update
  #   restart: no
  #   user: 1000:1000
  #   volumes:
  #     - ./jenkins_home:/var/jenkins_home
  #     - ./jenkins_agent:/home/jenkins
  #   command: sh -c "chown -R 1000:1000 /var/jenkins_home /home/jenkins && echo 'Volume permissions updated successfully.'"

  jenkins-server:
    image: jenkins/jenkins:latest
    container_name: jenkins-server
    restart: always
    user: 1000:1000
    environment:
      # Отключаем Content Security Policy (CSP) для отображения CSS стилей в отчетах HTML Publisher
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=""
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8010:8080
      - 50000:50000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    # depends_on:
    #   volume-permissions-update:
    #     condition: service_completed_successfully

  jenkins-agent:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: lifailon/jenkins-agent:latest
    container_name: jenkins-agent
    restart: always
    user: 1000:1000
    environment:
      - JENKINS_URL=${JENKINS_SERVER_URL}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
      - JENKINS_SECRET=${JENKINS_SECRET}
    volumes:
      - ./jenkins_agent:/home/jenkins
      # Пробрасываем сокет для доступа к Docker на агенте
      - /var/run/docker.sock:/var/run/docker.sock
    # Добавляем в группу Docker на хосте для доступа к сокету: getent group docker | cut -d: -f3
    group_add:
        - 110
    depends_on:
      jenkins-server:
        condition: service_healthy