# htpasswd -nbB admin DozzleAdmin
# htpasswd -nbB guest guest
users:
  admin:
    name: "admin"
    password: "$2y$05$ZpnjEolfXVcG53VrUtoELeu1zS9jDcSrtnk4J3iucEbYY3fOfTKOu"
  guest:
    name: "guest"
    password: "$2y$05$jSKf6v.ZhtKQEyuEgws0iuPhtviWjkDfEYK8yZ68wDeqvHzWpFuoG"